//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xna_metrobus {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Ayar : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ayar defaultInstance = ((Ayar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ayar())));
        
        public static Ayar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int FrekansSn {
            get {
                return ((int)(this["FrekansSn"]));
            }
            set {
                this["FrekansSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float SimulasyonHizi {
            get {
                return ((float)(this["SimulasyonHizi"]));
            }
            set {
                this["SimulasyonHizi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ToplamOtobusSayisi {
            get {
                return ((int)(this["ToplamOtobusSayisi"]));
            }
            set {
                this["ToplamOtobusSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DuraktaBeklemeSuresi {
            get {
                return ((int)(this["DuraktaBeklemeSuresi"]));
            }
            set {
                this["DuraktaBeklemeSuresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int EkranGenisligi {
            get {
                return ((int)(this["EkranGenisligi"]));
            }
            set {
                this["EkranGenisligi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int EkranYuksekligi {
            get {
                return ((int)(this["EkranYuksekligi"]));
            }
            set {
                this["EkranYuksekligi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MaxOtobusHiziKmSaat {
            get {
                return ((int)(this["MaxOtobusHiziKmSaat"]));
            }
            set {
                this["MaxOtobusHiziKmSaat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float OtobusHizlanmaIvmesi {
            get {
                return ((float)(this["OtobusHizlanmaIvmesi"]));
            }
            set {
                this["OtobusHizlanmaIvmesi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float OtobusYavaslmaIvmesi {
            get {
                return ((float)(this["OtobusYavaslmaIvmesi"]));
            }
            set {
                this["OtobusYavaslmaIvmesi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int FrameRate {
            get {
                return ((int)(this["FrameRate"]));
            }
            set {
                this["FrameRate"] = value;
            }
        }
    }
}
